import { createServerSupabaseClient } from '@/lib/supabase/server'
import AgreementForm from '@/components/agreement-form'

export const metadata = { title: 'Employment Agreement | On The Spot Repair', robots: { index: false, follow: false } }

export default async function AgreementPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params
  const supabase = createServerSupabaseClient()
  const { data: agreement } = await supabase.from('agreements').select('id,signed_at,created_at').eq('token', token).maybeSingle()
  if (!agreement || Date.now() - new Date(agreement.created_at).getTime() > 7 * 24 * 60 * 60 * 1000) return <main className="mx-auto max-w-2xl px-6 py-24"><h1 className="text-3xl font-black uppercase">Agreement unavailable</h1><p className="mt-4 text-muted-foreground">This link is invalid or has expired.</p></main>
  const { data: application } = await supabase.from('applications').select('full_name,position').eq('id', agreement.id).single()
  return <main className="mx-auto max-w-3xl px-6 py-16"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">On The Spot Repair</p><h1 className="mt-3 text-4xl font-black uppercase">Employment agreement</h1><p className="mt-4 text-muted-foreground">Prepared for {application?.full_name} — {application?.position}</p><article className="mt-8 border border-border bg-card p-6 leading-7"><p>This agreement confirms the employment terms discussed with the On The Spot Repair team. Employment is at will, meaning either you or the company may end employment at any time, with or without notice, subject to applicable law.</p><h2 className="mt-6 text-lg font-bold uppercase">Workplace expectations</h2><p className="mt-2">You agree to bring and maintain the tools required for your position, follow professional conduct standards, operate company or customer vehicles safely, protect confidential business information, and comply with our drug-free workplace policy.</p><h2 className="mt-6 text-lg font-bold uppercase">Term and benefits</h2><p className="mt-2">The first 90 days are a probationary period. Where offered, the company may provide a tool allowance and ASE certification benefits. A limited 12-month, 30-mile non-compete may apply to competitive mobile repair work to the extent permitted by Georgia law and as separately explained by the hiring team.</p><p className="mt-5">Your electronic signature confirms your intent to accept the agreement presented to you.</p></article>{agreement.signed_at ? <p className="mt-8 border border-primary/40 p-5 text-primary">This agreement was signed successfully.</p> : <AgreementForm token={token} />}</main>
}
