import { createServerSupabaseClient } from '@/lib/supabase/server'
import AgreementForm from '@/components/agreement-form'

export const metadata = { title: 'Employment Agreement | On The Spot Repair', robots: { index: false, follow: false } }

export default async function AgreementPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params
  const supabase = createServerSupabaseClient()
  const { data: agreement } = await supabase.from('agreements').select('id,signed_at,created_at,start_date,hourly_wage,offered_position').eq('token', token).maybeSingle()
  if (!agreement || Date.now() - new Date(agreement.created_at).getTime() > 7 * 24 * 60 * 60 * 1000) return <main className="mx-auto max-w-2xl px-6 py-24"><h1 className="text-3xl font-black uppercase">Agreement unavailable</h1><p className="mt-4 text-muted-foreground">This link is invalid or has expired.</p></main>
  const { data: application } = await supabase.from('applications').select('full_name,position').eq('id', agreement.id).single()
  const startDate = new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(`${agreement.start_date}T00:00:00Z`))
  const hourlyWage = Number(agreement.hourly_wage).toFixed(2)

  return <main className="mx-auto max-w-3xl px-6 py-16"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">On The Spot Repair</p><h1 className="mt-3 text-4xl font-black uppercase">At-Will Employment Agreement</h1><p className="mt-4 text-muted-foreground">Prepared for {application?.full_name} — {agreement.offered_position}</p>
    <article className="mt-8 border border-border bg-card p-6 leading-7"><h2 className="text-xl font-bold uppercase">Employment Agreement — On The Spot Repair Services &amp; Tires Inc</h2>
      <dl className="mt-6 grid gap-2"><div><dt className="inline font-bold">Employer: </dt><dd className="inline">On The Spot Repair Services &amp; Tires Inc</dd></div><div><dt className="inline font-bold">Employer Address: </dt><dd className="inline">990 2nd Street, Unadilla, GA 31091</dd></div><div><dt className="inline font-bold">Employee Name: </dt><dd className="inline">{application?.full_name || '________________'}</dd></div><div><dt className="inline font-bold">Position: </dt><dd className="inline">{agreement.offered_position}</dd></div><div><dt className="inline font-bold">Start Date: </dt><dd className="inline">{startDate}</dd></div><div><dt className="inline font-bold">Compensation: </dt><dd className="inline">${hourlyWage} per hour, paid biweekly, less required withholdings and authorized deductions.</dd></div><div><dt className="inline font-bold">Classification: </dt><dd className="inline">Hourly, nonexempt.</dd></div><div><dt className="inline font-bold">Work Location: </dt><dd className="inline">990 2nd Street, Unadilla, GA 31091, and other assigned service locations.</dd></div></dl>
      <h3 className="mt-7 text-lg font-bold uppercase">Terms &amp; Conditions</h3><div className="mt-4 space-y-4">
        <p><strong>At-Will Employment.</strong> Employment is for no definite period and is at will. Either you or On The Spot Repair Services &amp; Tires Inc may end the employment relationship at any time, with or without cause or advance notice, subject to applicable law. Nothing in this agreement, the introductory period, or any Company policy creates a promise of employment for a specific duration. Only a written agreement signed by the Company’s CEO may alter the at-will relationship.</p>
        <p><strong>90-Day Introductory Period.</strong> Your first 90 calendar days are an introductory period during which the Company will evaluate attendance, punctuality, job performance, safety, dependability, conduct, and overall suitability. The Company may extend this period. Completing it does not guarantee continued employment, change at-will status, or require progressive discipline before employment ends.</p>
        <p><strong>Schedule, Attendance, and Timekeeping.</strong> Regular shop hours are Monday through Friday, 8:00 AM to 5:00 PM, and Saturday, 8:00 AM to 12:00 PM; the shop is closed Sunday. Your assigned schedule may vary within business needs and may include on-call emergency service outside regular shop hours. You must report as scheduled, be ready to work on time, promptly notify the designated supervisor when delay or absence is unavoidable, accurately record all working time—including compensable emergency-service and on-call time—and never work off the clock. Attendance requirements are administered subject to approved leave, reasonable accommodation, and other protections required by law.</p>
        <p><strong>Pay and Overtime.</strong> You will be paid for all hours worked. As a nonexempt employee, you will receive overtime compensation required by applicable law, generally one and one-half times your regular rate for hours worked over 40 in a workweek. Overtime should be approved in advance, but all hours actually worked must still be reported.</p>
        <p><strong>Conditions of Employment.</strong> This offer and continued employment are conditioned on verification of identity and authorization to work in the United States, and on satisfactory completion of job-related driving-record, background, and drug screening conducted in accordance with applicable law and Company policy. Where a third-party consumer report is used, the Company will provide any separate disclosure, authorization, pre-adverse-action notice, report copy, rights summary, and final notice required by law. This agreement itself is not an authorization to obtain a consumer report.</p>
        <p><strong>Duties and Professional Conduct.</strong> You will perform the duties of your position and other lawful, reasonable assignments. You are expected to communicate professionally, treat customers and coworkers respectfully, cooperate with work assignments, protect customer property, be dependable and responsible, and refrain from threatening, abusive, discriminatory, retaliatory, dishonest, or seriously disruptive conduct.</p>
        <p><strong>Safety.</strong> You must follow all safety procedures, use required protective equipment, promptly report injuries, hazards, damaged equipment, and vehicle incidents, and operate tools, lifts, machinery, and vehicles only when trained and authorized.</p>
        <p><strong>Tools, Uniform, and Company Property.</strong> You are expected to maintain and bring the hand tools identified by the Company as reasonably necessary for the position. The Company provides a uniform, lifts, diagnostic equipment, and designated specialty tools. You must safeguard and return Company property upon request or when employment ends. Any deduction from wages will be made only when lawfully authorized.</p>
        <p><strong>Vehicle Operation.</strong> You must maintain a valid driver’s license appropriate for assigned duties and promptly disclose any suspension or restriction affecting your ability to drive for work. A CDL is not required for this position. You must follow Company safety and authorization rules when operating customer or Company vehicles.</p>
        <p><strong>Confidentiality.</strong> During and after employment, you must protect nonpublic customer information, security information, trade secrets, and other confidential business information obtained through work. This provision does not prohibit discussing wages, hours, or working conditions; reporting suspected unlawful conduct; cooperating with a government investigation; or engaging in activity protected by law.</p>
        <p><strong>Drug and Alcohol Policy.</strong> You must comply with the Company’s written drug- and alcohol-free workplace and testing policies, if adopted and provided to you. Any testing will be administered in accordance with those policies and applicable law.</p>
        <p><strong>Benefits and Policies.</strong> No paid time off, insurance, allowance, reimbursement, or other benefit is promised by this agreement. If the Company later offers a benefit, eligibility and terms will be governed solely by the applicable written plan or policy, as amended from time to time. Company policies do not alter at-will employment.</p>
        <p><strong>Entire Agreement and Severability.</strong> This agreement contains the complete agreement concerning the subjects it addresses and replaces prior oral or written statements about those subjects. If any provision is found unenforceable, the remaining provisions remain effective to the extent permitted by law. Georgia law governs this agreement, without limiting rights that cannot lawfully be waived.</p>
        <p><strong>Electronic Signature and Acknowledgment.</strong> By checking the acknowledgment box, typing your full legal name, and submitting, you confirm that you had the opportunity to review this agreement, understand it, voluntarily agree to its terms, consent to use an electronic record and signature for this transaction, and intend your typed name to be your electronic signature. You may save or print this page before signing.</p><p><strong>Employer.</strong> On The Spot Repair Services &amp; Tires Inc, by Diore Lemond, CEO.</p>
      </div>
    </article>{agreement.signed_at ? <p className="mt-8 border border-primary/40 p-5 text-primary">This agreement was signed successfully.</p> : <AgreementForm token={token} />}
  </main>
}
